### ISSUE TITLE
SQLPanel: No SQL queries were recorded during this request

### ISSUE THREAD

**Issue by yassam** [djsutho/django-debug-toolbar-request-history#8] opened 2016-10-05 06:46 UTC
Trying the latest version of this in combination with Debug Toolbar 1.5.

When I click on all but the first request, the SQL Panel says "No SQL queries were recorded during this request".

The summary SQL entry on the right looks ok, e.g. "1624 queries in 1325.60ms", but when I click on the summary panel to get the main SQL display on the left, it says "No SQL queries..."

Is there something specific I need to do to get SQL queries recorded for all requests?

**Comment by djsutho** [comment] 2016-10-06 13:40
Are there any errors in the logs or JavaScript errors? Also can I get a list of other dependencies that are installed e.g. `pip freeze` ? Hopefully I'll have more time on the weekend to look at this.

**Comment by djsutho** [comment] 2016-10-11 14:24
Looks like something changed in the debug-toolbar in version 1.5. Until I can get a fix for this it should still work with version 1.4 though you might need to force install `sqlparse==0.1.19`. Hopefully I can get into this soon, just finding ramp-up time is quite high as I'm not working with django at the moment.

**Closed** 2016-10-22 06:32 UTC

**Comment by djsutho** [comment] 2016-10-22 06:37
@yassam I think this should be fixed in the latest version. It looks like the problem was caused by the introduction of the `generate_stats` method in django-debug-toolbar with this PR https://github.com/jazzband/django-debug-toolbar/pull/731. I've added compatibility for this now so would you be able to test if this has fixed your problem?
